### ISSUE TITLE
Behavior in the TOC

### ISSUE THREAD

**Issue by damienld22** [zetapush/documentation#63]
Which behavior for the table of content ? 

1. The current behavior (We can't folding up the menu when we click on an opened title but it folds when clicking on another title)
2. We can fold up a menu if we click again on an opened title of the corresponding section. All other opened titles stay opened until user clicks on it to explicitely close it
3. We can fold up a menu if we click again on an opened title of the corresponding section. All other opened titles are closed as soon as any title is opened

**Comment by michelje** [comment]
2

**Comment by dezmou** [comment]
2

**Comment by ghoullier** [comment]
2

**Comment by juliecroyal** [comment]
allez, juste pour ne pas faire comme tout le monde : 3
