### ISSUE TITLE
Some old configuration sample in documentation

### ISSUE THREAD

**Issue by cedric-legallo** [zetapush/documentation#83]
In the 10.3.2.3 section : https://zetapush.github.io/documentation/#_configure_your_project_to_use_an_existing_application

the front/index.js configuration show an obsolete sandboxId field.
I did not made any PR because i dunno if you want an empty call to WeakClient
```
new ZetaPushWeakClient();
```
or a properly configurated one : 
```
const client = new ZetaPush.WeakClient({
    appName: <yourAppName>,
    platformUrl: <optionalUrl>
});
```

**Comment by ghoullier** [comment]
It's seems it's a browser cache problem. Can you update your page with a force reload (ctrl+mal+F5/R)?

**Comment by cedric-legallo** [comment]
Reproduced in Porn Mode !
it is the sample just above : https://zetapush.github.io/documentation/#_worker not the one in 11.1.2
